steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bagisto', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bagisto']

  # Run database migrations
  - name: 'gcr.io/google-appengine/exec-wrapper'
    args:
      - '-i'
      - 'gcr.io/$PROJECT_ID/bagisto'
      - '-s'
      - '$PROJECT_ID:$_REGION:$_INSTANCE_NAME'
      - '--'
      - 'php'
      - 'artisan'
      - 'migrate'
      - '--force'

images:
  - 'gcr.io/$PROJECT_ID/bagisto'
